platform :ios, '7.0'
pod 'AFNetworking', '~> 2.3'
pod 'MBProgressHUD', '~> 0.8'
pod 'Reachability', '~> 3.1'
pod 'CocoaSecurity', '~> 1.2'
pod 'SDWebImage', '~> 3.7'
pod 'WebViewJavascriptBridge', '~> 4.1'
pod 'IDMPhotoBrowser', '~> 1.4'
pod 'DACircularProgress', '~> 2.2'
pod 'pop', '~> 1.0'

